resources:
  repositories:
    - repository: templates
      type: github
      name: yuzp1996/application
      ref: refs/heads/master # optional ref to pin to
      endpoint: zpyu

extends:
    template: common.yml@templates
