# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


jobs:
- job: Start
  steps: 
  - script: echo "start"
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: include-npm-steps.yml  # Template reference
- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - template: include-npm-steps.yml  # Template reference
- job: End
  steps: 
  - script: echo "end"


