# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- stop

resources:
  repositories:
    - repository: templates
      type: github
      name: yuzp1996/application
      ref: refs/heads/master # optional ref to pin to
      endpoint: zpyu

jobs:
- template: common.yml@templates  # Template reference
  parameters:
    vmImage: 'windows-latest'
